### ISSUE TITLE
The selector cannot enter direct access mode as DF2:

### ISSUE THREAD

**Issue by patrikaxelsson** [jfdelnero/HXCFE_file_selector#1]
I have my gotek with the HxC firmware mounted in an extra-drive chassis. It works fine in all aspects on my A500. On both my A2000 and A4000, it works fine as a drive - it serves the adf images I have added to slots using the selector on my A500 perfectly, however the selector doesn't work on either the A2000 or A4000.

What happens when you start the selector is that it shows its screen, then you hear the internal DF0: drive grind a bit, then after a while you see the green access on the gotek light up briefly, but it never enters direct access mode (I still see slot 000 on the display). After that the selector shows an empty box in the middle.

The A2000 and A4000 has very different configurations. The A2000 has a GVP030 card and the A4000 has a CSPPC060 card. I have also tried the A2000 with the original 68000 and that makes no difference for this problem. What is common between them though is that both are big-box amigas with one internal drive as DF0:, so the gotek as first extra-drive turns up as DF2:.

The A2000 when running the original 68000 matches the A500 where the selector works fine more or less 100% (all machines are using kickstart 3.1), the only difference I can see is that the gotek becomes DF1: on the A500 but DF2: on the A2000.

Using the HxCGotekAlpha firmware now, but the issue was the same with the previous V3_0_8_2a.

![selector fail](https://cloud.githubusercontent.com/assets/12885607/21198525/09b5a650-c240-11e6-84e5-1087826e3d3c.jpg)

**Comment by jfdelnero** [comment]
Hi,

Can you retry with the latest alpha version and tell me what is the error message ?

http://hxc2001.com/download/floppy_drive_emulator/HxCGotekAlphaTrial.zip

**Comment by patrikaxelsson** [comment]
`ERROR: init_fdc drive 2 -> failure while seeking the track 00!`

**Comment by jfdelnero** [comment]
Ok thanks,
This should be now fixed with the last alpha version : 

http://hxc2001.com/download/floppy_drive_emulator/HxCGotekAlphaTrial.zip

**Comment by patrikaxelsson** [comment]
Works with the latest update, thanks!

**Comment by jfdelnero** [comment]
Ok then issue closed. 
Thanks for reporting this issue.
