### ISSUE TITLE
Possibly noiseless selector startup

### ISSUE THREAD

**Issue by patrikaxelsson** [jfdelnero/HXCFE_file_selector#2]
This is not an issue as in something that doesn't work, but some thoughts regarding an idea for an  improvement.

After you solved #1, I have started the selector on my A2000 more times than healthy in such short time. On my A2000, where the gotek is DF2:, there is a noticeable grinding from DF0: during the selector startup. As I understand from the [selector init code](https://github.com/jfdelnero/HXCFE_file_selector/blob/master/fectrl.c#L1725), it will call test_drive() which detects a HxC gotek by doing various seek tests until it finds the first matching drive. This is done in the fixed drive order 0 - 1 - 2 - 3, which explains the DF0: grinding noises before it finds the gotek on DF2:.

If the selector knew which drive number it started from, it could start calling test_drive() from that number instead which would remove the noises by not testing irrelevant drives. It should also reduce the selector init time if the gotek isn't on DF0: as in this case.

It is actually quite easy to ask the os about this. Wrote some example code to demonstrate it:
```C
#include <stdio.h>

#include <exec/exec.h>
#include <dos/dos.h>

#include <proto/exec.h>
#include <proto/dos.h>

/* Compile with: vc +kick13 -o UnitNumberTest UnitNumberTest.c */

/*
* Returns the unit number of the underlying device of a filesystem lock.
* Returns -1 on failure.
*/
LONG GetUnitNumFromLock(BPTR lock) {
	LONG unitNum = -1;
	if(lock != 0) { 
		struct InfoData *infoData = AllocMem(sizeof(struct InfoData), MEMF_ANY);
		if(NULL != infoData) {
			if(Info(lock, infoData)) {
				unitNum = infoData->id_UnitNumber;
			}
			FreeMem(infoData, sizeof(struct InfoData));
		}
	}
	return unitNum;
}

/*
* Returns the unit number of the underlying device of a filesystem path.
* Returns -1 on failure.
*/
LONG GetUnitNumFromPath(char *path) {
	LONG unitNum = -1;
	BPTR lock = Lock(path, ACCESS_READ);
	if(lock != 0) {
		unitNum = GetUnitNumFromLock(lock);
		UnLock(lock);
	}
	return unitNum;
}

UWORD GetLibraryVersion(struct Library *library) {
	return library->lib_Version;
}

int main(int argc, char *argv[]) {
	LONG startedFromUnitNum = GetLibraryVersion((struct Library *) DOSBase) >= 36 ?
		GetUnitNumFromLock(GetProgramDir()) :
		GetUnitNumFromPath(argv[0]);

	LONG unitNum = startedFromUnitNum >= 0 ?
		startedFromUnitNum :
		0;

	LONG count = 0;

	printf("Started from unit number: %ld\n", startedFromUnitNum);

	while(count++ < 4) {
		if(unitNum > 3) {
			unitNum = 0;
		}

		printf("Current unit number: %ld\n", unitNum);

		unitNum++;
	}

	return 0;
}
```

Observe that it is simpler to get the lock from the filesystem the executable is located in with 2.0/V36 and above, for versions below the lock has to be created from a suitable string - using the startup code created argv[0] pointing to the exe here.

Output example: [UnitNumberTest.txt](https://github.com/jfdelnero/HXCFE_file_selector/files/656100/UnitNumberTest.txt)

As you see from the output there is one caveat - [Info()](http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_3._guide/node017D.html) doesn't tell the device name, so say you start the selector from your second hard drive (scsi.device unit 1), the result will be the same as if you started it from DF1:, however it would still find the gotek by scanning through the drives and it feels like an acceptable compromise as you generally start the selector from the gotek.

Also if I am not mistaken, using this method would enable support for running the selector on several goteks in the same system - just launch the selector from the gotek you want to select on.

**Comment by jfdelnero** [comment]
I have added and adapted the code to the latest alpha version : 
http://hxc2001.com/download/floppy_drive_emulator/HxCGotekAlphaTrial.zip

Tested and working on A600 (lib v37)

Also tested on A500. Unfortunately GetUnitNumFromPath doesn't work yet due to an issue with libnix. argv/argc are empty/null. i had to patch libnix some years ago to make it compatible with A1000/A500 machines... 
Anyway this still a minor issue since the function start to test the drive 0 in this case.

Thanks

**Comment by patrikaxelsson** [comment]
Great stuff, starts completely silent now and much quicker!

I realized I forgot to add a NULL-check to GetUnitNumFromPath() for a possible NULL argv[0] case - Lock() used inside it does not have a check for NULL and gives enforcer hits for reading from address 0 and onwards in that case.

**Comment by patrikaxelsson** [comment]
Btw, apart from the NULL-check I forgot, I noticed one thing when looking at the [commit](https://github.com/jfdelnero/HXCFE_file_selector/commit/3d12ed79d6ac7865f976402f0ffb01a75f859829):
If GetUnitNumFromLock() or GetUnitNumFromPath() fails with -1, it will start by calling test_drive() for unit 3 (`(-1 + 0) & 0x3`). It will still find the drive on the next iteration, but 0 would be a better default to avoid an extra test_drive() delay on error as drive number 3 is the most unlikely to be populated.

**Comment by jfdelnero** [comment]
path check and start from 0 in case of error added to the latest release.

**Comment by patrikaxelsson** [comment]
👍
