### ISSUE TITLE
Feature Request: Allow quit without reboot

### ISSUE THREAD

**Issue by n9yty** [jfdelnero/HXCFE_file_selector#5]
Looking for a way to use this when started from a hard drive. It seems that I can run the program, although it pretty much takes over the system and there seems to be no way to quit except a reboot.

The idea would be to be able to copy different ADF files to the USB drive (on another system) and pick them to mount as floppies without having to restart the Amiga (in my case).

I am using an Amiga, I don't know if this would be useful on other systems as well.

Thanks for the consideration. I don't have a build environment set up for this, and don't see any build notes, or else I would take a peek at it myself, although that could take a long time. LOL

**Comment by sonicthewedge** [comment]
Ahoy.

Excellent suggestion!

I contrived a similar plan to achieve just this without the need for modification to the Gotek software (which I have been building elsewhere). I concluded that this was probably the best if not the only way.

My approach involves the crafty combination of:

- Pi Zero SMB mounted USB gadget and modified USB cable
- Windoze Gotek SELECTOR.ADF editor
- OLED Gotek hardware mod

This will do what you want to do in some style and you can look forward to multiple FDD support in one Gotek.

If you need answers to specific questions, I am happy to try to provide them!

**Comment by jfdelnero** [comment]
@sonicthewedge 

Your answer seems off the subject here. The question is how to quit the file selector without rebooting the Amiga. 
Btw there is not point to use the HxC File selector nor any other software when you have an networked usb stick emulator based on a Pi... Anyway not with my solution : all is handled by the Pi itself : file images conversion (if needed) and list generation from the embedded web page and samba/ftp folder.
And technically the Pi itself can even replace completely the Gotek ;)

Back to the subject.

**Comment by jfdelnero** [comment]
@n9yty 

Which firmware version are you using ? No OLED / LCD Screen on your emulators ?
The best modes for this usage this the "normal mode" with an OLED/LCD screen or the indexed mode.

Anyway the modifications shouldn't too hard to do : i didn't takeover much stuff. i just need to close/restore the screen context and set the normal timeout to amiga floppy driver.

**Comment by sonicthewedge** [comment]
If you run the file selector on a PC and access the Gotek over the network by using the a Pi Zero as the USB storage device, this absolutely answer the question.  You misrepresent the question.  You can change which ADF files are in which slots and swap to whichever one you want without rebooting.

**Comment by jfdelnero** [comment]
@sonicthewedge : Then you are talking about something else without any point with the current repository : The current file selector run on the Amiga/Atari ST and currently need a machine reboot once launched. This is what is pointed by @n9yty.  Although it can also be run on Linux/Windows, it is currently unable to work on networked drives/ftp/samba. The Windows/Linux version need to access to the stick directly.

@n9yty : Currently "fixing" the issue. FYI the Linux/Windows version can also be used as workaround for your need (and no Pi is needed here ;) ). Just launch the software to mount the stick on the PC. You can then assign the slots.

**Comment by jfdelnero** [comment]
@n9yty : Please find attached the Amiga autoboot.hfe with the "quit" feature. To leave the file selector select the corresponding function in the settings menu or press F4. Tested on a stock Amiga 600.

Let me know if all is working fine on your machine.

[AUTOBOOT.zip](https://github.com/jfdelnero/HXCFE_file_selector/files/2718361/AUTOBOOT.zip)

EDIT : 
new autoboot posted on your hxc forum thread too  ;) :
http://torlus.com/floppy/forum/viewtopic.php?f=5&t=3480&p=19485#p19485

**Comment by sonicthewedge** [comment]
Gave it a crack. Giving up. 

@n9yty I can give you more details if you are keen.

**Comment by n9yty** [comment]
Thank you. I will test, but cannot do it right now. The Pi option might be an interesting idea, but I agree it is totally removed from the scope of this repo and my request. As for making changes outside of the Amiga, I run MacOS and don’t think the tools for managing things are there... maybe WINE or other option, but it seemed easier to just have the Amiga program be able to make the changes and quit. :)

Edit: Maybe there is a MacOS version of the config manager, I will look at that option as well. Thank you for your great work!

**Comment by jfdelnero** [comment]
Try this version instead : it has a better screen handling.

[AUTOBOOT.zip](https://github.com/jfdelnero/HXCFE_file_selector/files/2719419/AUTOBOOT.zip)

Reminder : 
Press Left-Amiga+N keys to switch to the Workbench.
Press Left-Amiga+M keys to switch back to the HxC File selector (or any other Workbench friendly full screen software...).

You can drag/scroll the HxC File selector with the upper bar.
 
![multitasking_hxcfeselector](https://user-images.githubusercontent.com/11471394/50574133-56b54100-0de2-11e9-90dd-f4b966f429cc.png)

**Comment by n9yty** [comment]
This version works very well!  I think the only thing I noticed is that the F4 key is not documented in the help. I'm glad you mentioned it before or I would not have know which key to use to exit. :)  I REALLY appreciate your quick response and for adding this feature.

**Comment by jfdelnero** [comment]
Yes i need to update the help pages. Will do it for the next release. Thanks for having reminded me this feature and the tests !

**Comment by jfdelnero** [comment]
Ok i have released the new version with one change : i finally removed the new specific "quit" key and menu entry ;). Just use the old "save & reboot" or "reboot" keys. If you have launched the file selector from the Workbench, it will just exit without rebooting the machine. This is less prone to possible user error ;) :

https://github.com/jfdelnero/HXCFE_file_selector/releases/tag/HXCFE_file_selector_V1_89
