### ISSUE TITLE
Atari ST AUTOBOOT: Keyboard layout is hard coded to AZERTY

### ISSUE THREAD

**Issue by bfollowell** [jfdelnero/HXCFE_file_selector#6]
Jean, I'm not certain how it has escape everyone's notice until now, but the keymap.h file hard codes input to an AZERTY style keyboard, naturally, since you're French! I guess the only place this really comes into play is when using the search function.

I have no idea how to compile the source files or create a new AUTOBOOT file, but I did locate the keymap.h and was able to modify it with the correct U.S/U.K. QWERTY style scan codes.

Would you be able to use this to create a QWERTY compatible version of AUTOBOOT for Atari ST users?

Thank you!
[keymap.zip](https://github.com/jfdelnero/HXCFE_file_selector/files/4533514/keymap.zip)

**Comment by jfdelnero** [comment]
Already done in the latest versions. I don't use hardcoded table(s) anymore. I use the normal TOS way to support all keyboard layouts correctly now.

**Comment by bfollowell** [comment]
OK. I was using the latest version when I originally posted this. I haven't updated since then though. I'll update soon.

Thanks!
